name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test jacocoTestReport
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Test coverage report
        if: always()
        uses: ogotalski/test-coverage-report@8311ae68f08da8ebb72f8154111b8df2633ce320
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml,${{ github.workspace }}/MathUtils/build/reports/jacoco/test/jacocoTestReport.xml
          sourcePaths: ${{ github.workspace }}/src/main/kotlin,${{ github.workspace }}/MathUtils/src/main/java
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true